# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Logitmcmc_PG <- function(y, Xmat, m0, P0, start_vec, n_burnin, n_sample, thin) {
    .Call(`_SemiCompRisksBin_Logitmcmc_PG`, y, Xmat, m0, P0, start_vec, n_burnin, n_sample, thin)
}

rpg1z_devroye <- function(z) {
    .Call(`_SemiCompRisksBin_rpg1z_devroye`, z)
}

WeibUnimcmc <- function(y, delta, Xmat, hyper_vec, tuning_vec, start_vec, n_burnin, n_sample, thin) {
    .Call(`_SemiCompRisksBin_WeibUnimcmc`, y, delta, Xmat, hyper_vec, tuning_vec, start_vec, n_burnin, n_sample, thin)
}

WeibSCRmcmc <- function(y1, y_sm, delta1, delta1noD, delta_cr, delta_sm, Xmat1, Xmat2, Xmat3, hyper_vec, tuning_vec, start_vec, n_burnin, n_sample, thin, frail_path = "") {
    .Call(`_SemiCompRisksBin_WeibSCRmcmc`, y1, y_sm, delta1, delta1noD, delta_cr, delta_sm, Xmat1, Xmat2, Xmat3, hyper_vec, tuning_vec, start_vec, n_burnin, n_sample, thin, frail_path)
}

WeibSCRlogitmcmc <- function(y1, y_sm, delta1, delta1noD, delta_cr, delta_sm, delta1D_sub, Xmat1, Xmat2, Xmat3, XmatD, hyper_vec, tuning_vec, start_vec, sample_alpha1, sample_alpha2, sample_alpha3, sample_kappa1, sample_kappa2, sample_kappa3, sample_beta1, sample_beta2, sample_beta3, sample_betaD, sample_frail, sample_theta, accept_base, accept_frail, accept_beta1, accept_beta2, accept_beta3, LH_marg_mean_vec, invLH_marg_mean_vec, sample_logLH_marg, sample_logLHi_marg, LH_mean_vec, invLH_mean_vec, sample_logLH, sample_logLHi, move_vec, n_burnin, n_sample, thin, frail_ind, nGam_save, nlogLHi_save, gh_nodes, gh_weights) {
    invisible(.Call(`_SemiCompRisksBin_WeibSCRlogitmcmc`, y1, y_sm, delta1, delta1noD, delta_cr, delta_sm, delta1D_sub, Xmat1, Xmat2, Xmat3, XmatD, hyper_vec, tuning_vec, start_vec, sample_alpha1, sample_alpha2, sample_alpha3, sample_kappa1, sample_kappa2, sample_kappa3, sample_beta1, sample_beta2, sample_beta3, sample_betaD, sample_frail, sample_theta, accept_base, accept_frail, accept_beta1, accept_beta2, accept_beta3, LH_marg_mean_vec, invLH_marg_mean_vec, sample_logLH_marg, sample_logLHi_marg, LH_mean_vec, invLH_mean_vec, sample_logLH, sample_logLHi, move_vec, n_burnin, n_sample, thin, frail_ind, nGam_save, nlogLHi_save, gh_nodes, gh_weights))
}

WeibSCRlogitmcmc2 <- function(y1, y_sm, delta1, delta1noD, delta_cr, delta_sm, delta1D_sub, Xmat1, Xmat2, Xmat3, XmatD, hyper_vec, tuning_vec, start_vec, n_burnin, n_sample, thin) {
    .Call(`_SemiCompRisksBin_WeibSCRlogitmcmc2`, y1, y_sm, delta1, delta1noD, delta_cr, delta_sm, delta1D_sub, Xmat1, Xmat2, Xmat3, XmatD, hyper_vec, tuning_vec, start_vec, n_burnin, n_sample, thin)
}

